environment: dev

app_name: rest_api

server: 
  host: 0.0.0.0
  port: 8080
  base_path: /api/v1

databases:
  - host: localhost
    port: 27017
    database: mydb
    username: myuser
    password: mypassword
storages:
  - type: S3
    endpoint: localhost:9000
    access_key: myaccesskey
    secret_key: mysecretkey
    bucket: mybucket
    name: test-bucket
  - type: LOCAL
    name: local-storage
    base_path: ./runtime/storage

