environment: dev

app_name: rest_api

rest: 
  host: 0.0.0.0
  port: 8080
  base_path: /api/v1
  swagger:
    base_path: /
    file_path: docs/rest-api-v1.json
    path: "docs"
    title: "Kotak Email RestAPI"

databases:
  - host: localhost
    port: 27017
    database: kotakemail
    username: uloydev
    password: passwordnya
    name: mongodb-1
    type: MONGODB
storages:
  # - type: S3
  #   endpoint: localhost:9000
  #   access_key: myaccesskey
  #   secret_key: mysecretkey
  #   bucket: mybucket
  #   name: test-bucket
  - type: LOCAL
    name: local-storage
    base_path: ./../../runtime/storage
logging:
  level: INFO
  output: CONSOLE

