server: 
  host: 0.0.0.0
  port: 8080
  base_path: /api/v1
  debug: true

data_store:
  mongodb:
    host: localhost
    port: 27017
    database: mydb
    username: myuser
    password: mypassword
  minio:
    endpoint: localhost:9000
    access_key: myaccesskey
    secret_key: mysecretkey
    secure: false
    bucket: mybucket

